name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            artifact_name: rss-bot
            asset_name: rss-bot-linux-amd64
          - target: x86_64-pc-windows-msvc
            artifact_name: rss-bot.exe
            asset_name: rss-bot-windows-amd64.exe
          - target: x86_64-apple-darwin
            artifact_name: rss-bot
            asset_name: rss-bot-macos-amd64
          - target: arm-unknown-linux-gnueabihf
            artifact_name: rss-bot
            asset_name: rss-bot-raspbian-arm
          - target: aarch64-apple-darwin
            artifact_name: rss-bot
            asset_name: rss-bot-macos-arm64

    steps:
      - uses: actions/checkout@v3

      - name: Install cross
        run: cargo install cross

      - name: Build
        run: cross build --release --target ${{ matrix.target }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
